### ISSUE TITLE
MeeCast-Daemon fails to compile for SailfishOS < 4.2.0

### ISSUE THREAD

**Issue by Olf0** [Meecast/meecast#56]
From a log when compiling at the Sailfish-OBS targetting any SailfishOS release < 4.2.0 (down to 3.1.0, which is the oldest supported release at the Sailfish-OBS):
```
[  210s] g++ -Wl,-O1 -Wl,-rpath,/usr/share/meecastd/lib -o bin/meecastd meecastdaemon.o dbusadaptor.o dconfvalue.o mdconf.o mdconfitem.o moc_meecastdaemon.o moc_dbusadaptor.o moc_dconfvalue.o moc_mdconfitem.o   -lmlite5 -ldconf -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lsailfishapp -pie -rdynamic -lmdeclarativecache5 -lkeepalive -lQt5DBus -lQt5Quick -lQt5Gui -lQt5Qml -lQt5Network -lQt5Concurrent -lQt5Core -lGLESv2 -lpthread 
[  211s] /usr/bin/ld: mdconfitem.o: in function `MDConfItem::listDirs(QString const&) const':
[  211s] /home/abuild/rpmbuild/BUILD/harbour-meecast-1.1.39/meecast/meecastdaemon/../dconf/mdconfitem.cpp:126: undefined reference to `dconf_is_dir(char const*, _GError**)'
[  211s] /usr/bin/ld: mdconfitem.o: in function `MDConfItem::listItems(QString const&) const':
[  211s] /home/abuild/rpmbuild/BUILD/harbour-meecast-1.1.39/meecast/meecastdaemon/../dconf/mdconfitem.cpp:161: undefined reference to `dconf_is_key(char const*, _GError**)'
[  211s] collect2: error: ld returned 1 exit status
[  211s] make[1]: *** [Makefile:140: bin/meecastd] Error 1
[  211s] make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/harbour-meecast-1.1.39/meecast/meecastdaemon'
[  211s] make: *** [Makefile:617: sub-meecast-meecastdaemon-make_first-ordered] Error 2
[  211s] error: Bad exit status from /var/tmp/rpm-tmp.FN14L1 (%build)
```

I wonder what is going on here, because the two code locations in `meecast/dconf/mdconfitem.cpp` ([[1]](https://github.com/Meecast/meecast/blame/sailfishos/meecast/dconf/mdconfitem.cpp#L126) and [[2]](https://github.com/Meecast/meecast/blame/sailfishos/meecast/dconf/mdconfitem.cpp#L161)) are both part of a large block of code which was not altered for 10 years.

So I assume something must have been changed somewhere else causing this failure, but my C++ and QML programming skills are too little to understand what.

**Comment by vasvlad** [comment]
Fixed. Try it

**Comment by Olf0** [comment]
I let [the Sailfish-OBS try it](https://build.sailfishos.org/package/show/home:olf:MeeCast/MeeCast): Nice, it now also compiles on / for SailfishOS 3.3.0 to 4.1.0. :smiley:

On SailfishOS 3.1.0 to 3.2.1 the compilation [now exits with this error](https://build.sailfishos.org/package/live_build_log/home:olf:MeeCast/MeeCast/3.2.1_armv7hl/armv8el):
```
[  100s] src/meego-main.cpp:662:30: error: 'class Json::Value' has no member named 'asString'
[  100s]      if (val.get("sunset","").asString() != ""){
[  100s]                               ^
[  100s] src/meego-main.cpp:663:41: error: 'class Json::Value' has no member named 'asString'
[  100s]          sun_time = val.get("sunset","").asString();
[  100s]                                          ^
```

Please mind, that it is nice to restore the compilation for old SailfishOS releases (e.g. I am still using SailfishOS 3.2.1 on my Xperia X), it is not worth putting a lot of work into this, because there will be only very few users.  But if it is easy, please do it (then I can use a current MeeCast on my Xperia X, again).
