### ISSUE TITLE
MeeCast fails to compile for SailfishOS < 3.3.0

### ISSUE THREAD

**Issue by Olf0** [Meecast/meecast#58]
> > [MeeCast-Daemon fails to compile for SailfishOS < 4.2.0](https://github.com/Meecast/meecast/issues/56)
> 
> [Fixed. Try it](https://github.com/Meecast/meecast/issues/56#issuecomment-2218127313)

Thank you very much, I let [the Sailfish-OBS try it](https://build.sailfishos.org/package/show/home:olf:MeeCast/MeeCast): Nice, it now also compiles on / for SailfishOS 3.3.0 to 4.1.0. :smiley:

On SailfishOS 3.1.0 to 3.2.1 the compilation [now exits with this error](https://build.sailfishos.org/package/live_build_log/home:olf:MeeCast/MeeCast/3.2.1_armv7hl/armv8el):
```
[  100s] src/meego-main.cpp:662:30: error: 'class Json::Value' has no member named 'asString'
[  100s]      if (val.get("sunset","").asString() != ""){
[  100s]                               ^
[  100s] src/meego-main.cpp:663:41: error: 'class Json::Value' has no member named 'asString'
[  100s]          sun_time = val.get("sunset","").asString();
[  100s]                                          ^
[...]
[  100s] make[1]: *** [Makefile:227: meego-main.o] Error 1
[  100s] make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/harbour-meecast-1.1.39+sailfishos.20240709162004.2.g999d41fe4/omweather-fmi-fi-stations-db'
[  100s] make: *** [Makefile:58: sub-omweather-fmi-fi-stations-db-make_first-ordered] Error 2
[  100s] error: Bad exit status from /var/tmp/rpm-tmp.NtF7mN (%build)
```

This is in [lines 662 and 663 of `omweather-fmi-fi-stations-db/src/meego-main.cpp`](https://github.com/Meecast/meecast/blob/sailfishos/omweather-fmi-fi-stations-db/src/meego-main.cpp#L662-L663).  Again, [`git blame` shows this code as unaltered for 9 years](https://github.com/Meecast/meecast/blame/sailfishos/omweather-fmi-fi-stations-db/src/meego-main.cpp#L662-L663) (i.e. since long before SailfishOS 3.1.0), but OBS is known to be picky.

Please mind, that it is nice to restore the compilation for old SailfishOS releases (e.g. I am still using SailfishOS 3.2.1 on my Xperia X), but IMO it is not worth putting a lot of work into this, because there will be only very few users.  OTOH if it is easy, please do it (then I can use a current MeeCast on my Xperia X, again).

**Comment by Olf0** [comment]
Thanks!
Builds fine now for all SailfishOS releases supported by Sailfish-OBS and hence also the SailfishOS:Chum repository, see https://build.sailfishos.org/package/show/home:olf:MeeCast/MeeCast

I am in the process of updating the spec file (not ready yet!), see PR-draft #57.
